import os from 'os';
import path from 'path';
import type {
  Adapter,
  AdapterContext,
  AdapterResult,
  DegradedCapability,
  Plugin,
  PluginComponent,
} from '@rosetta/core';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sectionHeading(component: PluginComponent): string {
  const name = String(component.frontmatter.name ?? path.basename(component.sourcePath, '.md'));
  const description = component.frontmatter.description
    ? `\n\n> ${component.frontmatter.description}`
    : '';
  return `## ${name}${description}\n\n`;
}

// ---------------------------------------------------------------------------
// Adapter
//
// Codex CLI and OpenCode both use a single AGENTS.md (or CLAUDE.md for compat).
// All components are concatenated into one file with section headings.
// Hooks and MCP are omitted — neither has a runtime equivalent.
// ---------------------------------------------------------------------------

export const codexAdapter: Adapter = {
  harness: 'codex',
  displayName: 'Codex CLI / OpenCode',
  defaultRoots: {
    user:    os.homedir(),
    project: '.',
  },

  async adapt(plugin: Plugin, _ctx: AdapterContext): Promise<AdapterResult> {
    const degraded: DegradedCapability[] = [];
    const sections: string[] = [
      `# ${plugin.id}\n\n${plugin.description}\n\n`,
      `<!-- Generated by Rosetta from @rosetta/content@${plugin.version} -->\n\n`,
    ];

    for (const component of plugin.components) {
      const name = path.basename(component.sourcePath, '.md');

      switch (component.type) {
        case 'rule':
        case 'skill':
        case 'agent':
        case 'command':
          sections.push(sectionHeading(component) + component.body + '\n\n');
          if (component.type === 'agent') {
            degraded.push({
              component: 'agent',
              name,
              reason: 'Codex has no agent runtime. Included as a reference section in AGENTS.md.',
              disposition: 'partial',
            });
          }
          if (component.type === 'command') {
            degraded.push({
              component: 'command',
              name,
              reason: 'Codex has no slash command system. Included as a reference section in AGENTS.md.',
              disposition: 'partial',
            });
          }
          break;

        case 'hook':
          degraded.push({
            component: 'hook',
            name,
            reason: 'Codex has no hook system.',
            disposition: 'omitted',
          });
          break;

        case 'mcp':
          degraded.push({
            component: 'mcp',
            name,
            reason: 'Codex does not support MCP server configuration via AGENTS.md.',
            disposition: 'omitted',
          });
          break;
      }
    }

    return {
      harness: 'codex',
      files: [{ path: 'AGENTS.md', content: sections.join('') }],
      degraded,
    };
  },
};
