#!/usr/bin/env node
// Generate docs/coverage.md from the catalog — category coverage + per-plugin harness fidelity.
//
//   node scripts/coverage.ts        # writes docs/coverage.md (and prints a summary)
//
// Generated, never hand-maintained: it reads catalog/categories.json + marketplace.json and
// runs every adapter, so it can't drift from the catalog. Runs as native TypeScript.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { loadPlugin } from "../src/load.ts";
import { adapters } from "../src/adapters/index.ts";
import type { Fidelity } from "../src/contract.ts";

const ROOT = process.cwd();

interface Category {
  name: string;
  family: string;
}
interface PluginEntry {
  name: string;
  source: string;
  category: string;
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(join(ROOT, path), "utf8")) as T;
}

const categories = readJson<{ categories: Category[] }>("catalog/categories.json").categories;
const plugins = readJson<{ plugins: PluginEntry[] }>(".claude-plugin/marketplace.json").plugins;

// --- Category coverage -------------------------------------------------------
const byCategory = new Map<string, string[]>();
for (const c of categories) byCategory.set(c.name, []);
for (const p of plugins) byCategory.get(p.category)?.push(p.name);

const families: string[] = [];
for (const c of categories) if (!families.includes(c.family)) families.push(c.family);

const coveredCount = [...byCategory.values()].filter((ps) => ps.length > 0).length;

// --- Harness fidelity --------------------------------------------------------
const harnessNames = Object.keys(adapters);

function tally(report: { status: Fidelity }[]): string {
  const counts: Record<string, number> = {};
  for (const e of report) counts[e.status] = (counts[e.status] ?? 0) + 1;
  const parts = (["NATIVE", "DEMOTED", "INLINED", "SKIPPED"] as Fidelity[])
    .filter((s) => counts[s])
    .map((s) => `${counts[s]}${s[0]}`); // 1N, 2D, …
  return parts.join(" ") || "—";
}

const fidelityRows = plugins.map((p) => {
  const plugin = loadPlugin(join(ROOT, p.source));
  const cells = harnessNames.map((h) => tally(adapters[h].adapt(plugin).report));
  return { name: p.name, cells };
});

// --- Render ------------------------------------------------------------------
const lines: string[] = [];
lines.push("# Catalog coverage");
lines.push("");
lines.push("> Generated by `mise run coverage` (`node scripts/coverage.ts`) — do not edit by hand.");
lines.push("");
lines.push(
  `**${plugins.length} plugins · ${coveredCount} of ${categories.length} categories covered.**`,
);
lines.push("");

lines.push("## By category");
lines.push("");
for (const family of families) {
  lines.push(`### ${family}`);
  lines.push("");
  lines.push("| Category | Plugins |");
  lines.push("| --- | --- |");
  for (const c of categories.filter((x) => x.family === family)) {
    const ps = byCategory.get(c.name) ?? [];
    lines.push(`| ${c.name} | ${ps.length ? ps.join(", ") : "—"} |`);
  }
  lines.push("");
}

lines.push("## Harness fidelity");
lines.push("");
lines.push("Per plugin, the translation report for each harness (`N`ative · `D`emoted · `I`nlined · `S`kipped).");
lines.push("");
lines.push(`| Plugin | ${harnessNames.join(" | ")} |`);
lines.push(`| --- | ${harnessNames.map(() => "---").join(" | ")} |`);
for (const row of fidelityRows) {
  lines.push(`| ${row.name} | ${row.cells.join(" | ")} |`);
}
lines.push("");

const out = lines.join("\n");
writeFileSync(join(ROOT, "docs/coverage.md"), out);
console.log(`docs/coverage.md written — ${plugins.length} plugins, ${coveredCount}/${categories.length} categories covered.`);
